### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Scout henry",
  "address": "D- 197 NewYork",
  "dateOfBirth": "2002-09-16",
  "registeredDate": "2025-09-16",
  "email": "scout_bill@example.com"
}

###