### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Aviral Patel",
  "address": "D- 197 Avas vikas colony",
  "dateOfBirth": "2002-09-16",
  "email": "john.doe@example.com"
}

###